services:
  django:
    image: videobackend:0.9
    build: 
      context: ./config/django-image
    volumes:
      - ./:/usr/src/app:delegated
    environment:
      DB_HOST: ${DB_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_PORT: ${DB_PORT}
      DJANGO_SU_NAME: ${DJANGO_SU_NAME}
      DJANGO_SU_EMAIL: ${DJANGO_SU_EMAIL}
      DJANGO_SU_PASSWORD: ${DJANGO_SU_PASSWORD}
    ports:
      - "8000:8000"
    networks:
      - red
  postgres:
    image: postgres:16-bullseye
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data:/var/lib/postgresql/data:delegated
    ports:
      - ${DB_PORT}:5432
    networks:
      - red   
networks:
  red: