services:
  django:
    image: videobackend:0.1
    build: 
      context: ./config/django-image
    volumes:
      - ./:/usr/src/app:delegated
    ports:
      - "8000:8000"
    networks:
      - red

networks:
  red: